import { db } from '@/db';
import { citations } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();

    const sampleCitations = [
        // Document 1: Brown v. Board of Education citations
        {
            documentId: 1,
            title: 'Plessy v. Ferguson',
            x: 20,
            y: 30,
            citations: 450,
            year: 1896,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 1,
            title: 'Sweatt v. Painter',
            x: 35,
            y: 55,
            citations: 120,
            year: 1950,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 1,
            title: 'McLaurin v. Oklahoma',
            x: 60,
            y: 40,
            citations: 95,
            year: 1950,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 1,
            title: 'Bolling v. Sharpe',
            x: 45,
            y: 70,
            citations: 180,
            year: 1954,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 1,
            title: 'Cooper v. Aaron',
            x: 75,
            y: 25,
            citations: 220,
            year: 1958,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 1,
            title: 'Green v. County School Board',
            x: 55,
            y: 80,
            citations: 310,
            year: 1968,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        // Document 2: Miranda Rights citations
        {
            documentId: 2,
            title: 'Escobedo v. Illinois',
            x: 25,
            y: 45,
            citations: 280,
            year: 1964,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'Gideon v. Wainwright',
            x: 40,
            y: 65,
            citations: 520,
            year: 1963,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'Malloy v. Hogan',
            x: 55,
            y: 35,
            citations: 150,
            year: 1964,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'Dickerson v. United States',
            x: 70,
            y: 55,
            citations: 190,
            year: 2000,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'Berghuis v. Thompkins',
            x: 30,
            y: 75,
            citations: 85,
            year: 2010,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'J.D.B. v. North Carolina',
            x: 65,
            y: 20,
            citations: 72,
            year: 2011,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 2,
            title: 'Salinas v. Texas',
            x: 50,
            y: 85,
            citations: 68,
            year: 2013,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        // Document 3: Roe v. Wade citations
        {
            documentId: 3,
            title: 'Griswold v. Connecticut',
            x: 30,
            y: 40,
            citations: 650,
            year: 1965,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 3,
            title: 'Eisenstadt v. Baird',
            x: 45,
            y: 60,
            citations: 210,
            year: 1972,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 3,
            title: 'Planned Parenthood v. Casey',
            x: 60,
            y: 30,
            citations: 890,
            year: 1992,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 3,
            title: 'Stenberg v. Carhart',
            x: 50,
            y: 75,
            citations: 320,
            year: 2000,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 3,
            title: 'Gonzales v. Carhart',
            x: 75,
            y: 50,
            citations: 280,
            year: 2007,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            documentId: 3,
            title: 'Whole Woman\'s Health v. Hellerstedt',
            x: 40,
            y: 85,
            citations: 195,
            year: 2016,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(citations).values(sampleCitations);
    
    console.log('✅ Citations seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});